import { IGoat } from '@/types/goat';

export const goats: IGoat[] = [
  {
    goatId: 'a1b2c3d4',
    goatName: 'Bella',
    image: 'bella.jpg',
    amountBought: 150,
    status: 'alive',
    age: '4yrs3mo',
    dob: new Date('2020-03-15'),
    parent: '',
    gender: 'doe',
    numOfKids: 3,
    children: ['x1y2z3w4', 'q1w2e3r4', 't5y6u7i8'],
    healthIssues: [],
  },
  {
    goatId: 'e5f6g7h8',
    goatName: 'Rocky',
    image: 'rocky.jpg',
    amountBought: 200,
    status: 'alive',
    age: '5yrs',
    dob: new Date('2019-05-20'),
    parent: '',
    gender: 'buck',
    numOfKids: 12,
    children: ['a1b2c3d4', 'i9j8k7l6', 'm1n2b3v4'],
    healthIssues: ['limp'],
  },
  {
    goatId: 'i9j8k7l6',
    goatName: 'Daisy',
    image: 'daisy.jpg',
    amountBought: 175,
    status: 'alive',
    age: '3yrs1mo',
    dob: new Date('2021-01-10'),
    parent: 'e5f6g7h8',
    gender: 'doe',
    numOfKids: 2,
    children: ['o5p6q7r8', 's9t0u1v2'],
    healthIssues: [],
  },
  {
    goatId: 'm1n2b3v4',
    goatName: 'Max',
    image: 'max.jpg',
    amountBought: 180,
    status: 'sold',
    age: '3yrs',
    dob: new Date('2021-02-28'),
    parent: 'e5f6g7h8',
    gender: 'buck',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'o5p6q7r8',
    goatName: 'Luna',
    image: 'luna.jpg',
    amountBought: 0,
    status: 'alive',
    age: '11mo',
    dob: new Date('2023-04-05'),
    parent: 'i9j8k7l6',
    gender: 'doe',
    numOfKids: 0,
    children: [],
    healthIssues: ['allergies'],
  },
  {
    goatId: 's9t0u1v2',
    goatName: 'Charlie',
    image: 'charlie.jpg',
    amountBought: 0,
    status: 'alive',
    age: '11mo',
    dob: new Date('2023-04-05'),
    parent: 'i9j8k7l6',
    gender: 'buck',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'x1y2z3w4',
    goatName: 'Molly',
    image: 'molly.jpg',
    amountBought: 0,
    status: 'alive',
    age: '1yr7mo',
    dob: new Date('2022-07-12'),
    parent: 'a1b2c3d4',
    gender: 'doe',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'q1w2e3r4',
    goatName: 'Buddy',
    image: 'buddy.jpg',
    amountBought: 0,
    status: 'alive',
    age: '1yr7mo',
    dob: new Date('2022-07-12'),
    parent: 'a1b2c3d4',
    gender: 'buck',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 't5y6u7i8',
    goatName: 'Lily',
    image: 'lily.jpg',
    amountBought: 0,
    status: 'dead',
    age: '1yr7mo',
    dob: new Date('2022-07-12'),
    parent: 'a1b2c3d4',
    gender: 'doe',
    numOfKids: 0,
    children: [],
    healthIssues: ['pneumonia'],
  },
  {
    goatId: 'k9l8m7n6',
    goatName: 'Duke',
    image: 'duke.jpg',
    amountBought: 225,
    status: 'alive',
    age: '5yrs6mo',
    dob: new Date('2018-11-30'),
    parent: '',
    gender: 'buck',
    numOfKids: 8,
    children: ['p1o2i3u4', 'z9x8c7v6'],
    healthIssues: ['arthritis'],
  },
  {
    goatId: 'p1o2i3u4',
    goatName: 'Sophie',
    image: 'sophie.jpg',
    amountBought: 190,
    status: 'alive',
    age: '3yrs8mo',
    dob: new Date('2020-09-22'),
    parent: 'k9l8m7n6',
    gender: 'doe',
    numOfKids: 1,
    children: ['b5n6m7k8'],
    healthIssues: [],
  },
  {
    goatId: 'z9x8c7v6',
    goatName: 'Oreo',
    image: 'oreo.jpg',
    amountBought: 0,
    status: 'stolen',
    age: '3yrs8mo',
    dob: new Date('2020-09-22'),
    parent: 'k9l8m7n6',
    gender: 'buck',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'b5n6m7k8',
    goatName: 'Peanut',
    image: 'peanut.jpg',
    amountBought: 0,
    status: 'alive',
    age: '1yr2mo',
    dob: new Date('2023-02-14'),
    parent: 'p1o2i3u4',
    gender: 'doe',
    numOfKids: 0,
    children: [],
    healthIssues: ['underweight'],
  },
  {
    goatId: 'v3c4x5z6',
    goatName: 'Willow',
    image: 'willow.jpg',
    amountBought: 160,
    status: 'alive',
    age: '3yrs10mo',
    dob: new Date('2020-06-18'),
    parent: '',
    gender: 'doe',
    numOfKids: 4,
    children: ['l2k3j4h5', 'g6f7d8s9'],
    healthIssues: [],
  },
  {
    goatId: 'l2k3j4h5',
    goatName: 'Finn',
    image: 'finn.jpg',
    amountBought: 0,
    status: 'alive',
    age: '1yr8mo',
    dob: new Date('2022-08-09'),
    parent: 'v3c4x5z6',
    gender: 'buck',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'g6f7d8s9',
    goatName: 'Rosie',
    image: 'rosie.jpg',
    amountBought: 0,
    status: 'alive',
    age: '1yr8mo',
    dob: new Date('2022-08-09'),
    parent: 'v3c4x5z6',
    gender: 'doe',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'h8j7k6l5',
    goatName: 'Thor',
    image: 'thor.jpg',
    amountBought: 210,
    status: 'alive',
    age: '4yrs11mo',
    dob: new Date('2019-04-25'),
    parent: '',
    gender: 'buck',
    numOfKids: 5,
    children: ['p4o3i2u1', 'm9n8b7v6'],
    healthIssues: [],
  },
  {
    goatId: 'p4o3i2u1',
    goatName: 'Misty',
    image: 'misty.jpg',
    amountBought: 0,
    status: 'alive',
    age: '2yrs6mo',
    dob: new Date('2021-10-15'),
    parent: 'h8j7k6l5',
    gender: 'doe',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'm9n8b7v6',
    goatName: 'Oliver',
    image: 'oliver.jpg',
    amountBought: 0,
    status: 'consumed',
    age: '2yrs6mo',
    dob: new Date('2021-10-15'),
    parent: 'h8j7k6l5',
    gender: 'buck',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'w2e3r4t5',
    goatName: 'Nala',
    image: 'nala.jpg',
    amountBought: 170,
    status: 'alive',
    age: '3yrs10mo',
    dob: new Date('2020-07-07'),
    parent: '',
    gender: 'doe',
    numOfKids: 2,
    children: ['y6u7i8o9', 't4r5e6w7'],
    healthIssues: [],
  },
  {
    goatId: 'y6u7i8o9',
    goatName: 'Leo',
    image: 'leo.jpg',
    amountBought: 0,
    status: 'missing',
    age: '1yr3mo',
    dob: new Date('2023-01-20'),
    parent: 'w2e3r4t5',
    gender: 'buck',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 't4r5e6w7',
    goatName: 'Zoe',
    image: 'zoe.jpg',
    amountBought: 0,
    status: 'alive',
    age: '1yr3mo',
    dob: new Date('2023-01-20'),
    parent: 'w2e3r4t5',
    gender: 'doe',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'u8i7o6p5',
    goatName: 'Simba',
    image: 'simba.jpg',
    amountBought: 195,
    status: 'alive',
    age: '4yrs4mo',
    dob: new Date('2019-12-10'),
    parent: '',
    gender: 'buck',
    numOfKids: 7,
    children: ['h3j4k5l6', 'q9w8e7r6'],
    healthIssues: [],
  },
  {
    goatId: 'h3j4k5l6',
    goatName: 'Coco',
    image: 'coco.jpg',
    amountBought: 0,
    status: 'alive',
    age: '2yrs8mo',
    dob: new Date('2021-08-30'),
    parent: 'u8i7o6p5',
    gender: 'doe',
    numOfKids: 1,
    children: ['v2b3n4m5'],
    healthIssues: [],
  },
  {
    goatId: 'q9w8e7r6',
    goatName: 'Jack',
    image: 'jack.jpg',
    amountBought: 0,
    status: 'alive',
    age: '2yrs8mo',
    dob: new Date('2021-08-30'),
    parent: 'u8i7o6p5',
    gender: 'buck',
    numOfKids: 0,
    children: [],
    healthIssues: ['hoof rot'],
  },
  {
    goatId: 'v2b3n4m5',
    goatName: 'Mia',
    image: 'mia.jpg',
    amountBought: 0,
    status: 'alive',
    age: '11mo',
    dob: new Date('2023-05-12'),
    parent: 'h3j4k5l6',
    gender: 'doe',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'k7j6h5g4',
    goatName: 'Bailey',
    image: 'bailey.jpg',
    amountBought: 185,
    status: 'alive',
    age: '4yrs2mo',
    dob: new Date('2020-02-28'),
    parent: '',
    gender: 'doe',
    numOfKids: 3,
    children: ['d3f4g5h6', 's2d3f4g5'],
    healthIssues: [],
  },
  {
    goatId: 'd3f4g5h6',
    goatName: 'Toby',
    image: 'toby.jpg',
    amountBought: 0,
    status: 'alive',
    age: '1yr5mo',
    dob: new Date('2022-11-15'),
    parent: 'k7j6h5g4',
    gender: 'buck',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 's2d3f4g5',
    goatName: 'Ruby',
    image: 'ruby.jpg',
    amountBought: 0,
    status: 'alive',
    age: '1yr5mo',
    dob: new Date('2022-11-15'),
    parent: 'k7j6h5g4',
    gender: 'doe',
    numOfKids: 0,
    children: [],
    healthIssues: [],
  },
  {
    goatId: 'a5s6d7f8',
    goatName: 'Gus',
    image: 'gus.jpg',
    amountBought: 205,
    status: 'alive',
    age: '4yrs8mo',
    dob: new Date('2019-08-17'),
    parent: '',
    gender: 'buck',
    numOfKids: 9,
    children: ['j8k7l6h5', 'p0o9i8u7'],
    healthIssues: [],
  },
];
