import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import { SidebarExpandableProvider } from './contexts/SidebarExpandableContext';
import { Toaster } from 'react-hot-toast';
import { PasswordToggleProvider } from './contexts/PasswordToggleContext';

const nunito = Nunito({
  subsets: ['vietnamese'],
  weight: ['200', '300', '400', '500', '600', '700'],
  variable: '--font-nunito',
  display: 'swap',
  preload: true, // 👈 Preload the font
  adjustFontFallback: true, // 👈 Better fallback behavior
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={nunito.variable} suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background bg-[#f3f3f3] antialiased flex flex-col'
        )}>
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange>
          <PasswordToggleProvider>
            <SidebarExpandableProvider>{children}</SidebarExpandableProvider>
          </PasswordToggleProvider>
          <Toaster
            position='top-center'
            gutter={6}
            toastOptions={{
              success: {
                duration: 3000,
              },
              error: {
                duration: 5000,
              },
              style: {
                fontSize: '15px',
                padding: '10px 20px',
                backgroundColor: 'grey-0',
                color: 'grey-700',
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
